# Generated by Django 5.1.4 on 2026-09-24 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('executive_summary', 'Executive summary'), ('campaign_results', 'Campaign results'), ('department_summary', 'Department summary'), ('training_compliance', 'Training compliance'), ('risk_scores', 'Employee risk scores'), ('evidence_package', 'Compliance evidence package')], max_length=32)),
                ('file_format', models.CharField(max_length=8)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('as_of', models.DateTimeField(help_text='Every figure is computed from the event log as it stood at this moment.')),
                ('algorithm_version', models.CharField(max_length=32)),
                ('scope_label', models.CharField(max_length=200)),
                ('is_scoped', models.BooleanField(default=False, help_text="Built under a Department Manager's row scoping — only its author may see it.")),
                ('contains_employee_data', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'permissions': [('generate_report', 'Can generate aggregate (non-individual) reports'), ('export_employee_level', 'Can generate reports that name individual employees')],
                'indexes': [models.Index(fields=['kind', 'period_start', 'period_end'], name='reporting_g_kind_3a764c_idx')],
            },
        ),
    ]
