# Generated by Django 5.2.17 on 2026-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='is_scoped',
            field=models.BooleanField(default=False, help_text="Built under a Department Manager's row scoping — only its author and org-wide roles may see it."),
        ),
    ]
