# Generated by Django 5.2.17 on 2026-09-24 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_alter_generatedreport_is_scoped"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive summary"),
                            ("campaign_results", "Campaign results"),
                            ("department_summary", "Department summary"),
                            ("training_compliance", "Training compliance"),
                            ("risk_scores", "Employee risk scores"),
                            ("evidence_package", "Compliance evidence package"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly (last 7 days, sent Mondays)"),
                            ("monthly", "Monthly (previous month, sent on the 1st)"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="Email addresses, one per line or comma-separated."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_period_end",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
