# Generated by Django 5.1.4 on 2026-09-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gophish_campaign_id', models.CharField(blank=True, max_length=64, null=True)),
                ('template_name', models.CharField(help_text='Must match an existing Gophish email template name.', max_length=200)),
                ('landing_page_url', models.URLField(help_text="Landing page URL, per Gophish's create-campaign API.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('launched', 'Launched')], default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='employees.department')),
            ],
        ),
    ]
