# Generated by Django 5.1.4 on 2026-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='landing_page_name',
            field=models.CharField(default='', help_text='Must match an existing Gophish landing page name — distinct from the URL below.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='gophish_campaign_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
