# Generated by Django 5.1.4 on 2026-09-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_landing_page_name_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='training_module',
            field=models.ForeignKey(blank=True, help_text="Auto-assigned to an employee who fails this campaign's simulation (clicks or submits data).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='training.trainingmodule'),
        ),
    ]
