# Generated by Django 5.2.17 on 2026-09-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_campaign_options_campaign_approved_at_and_more"),
        ("employees", "0004_employee_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Invoice, Delivery, IT, HR, Credential reset.",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Gophish email template name.", max_length=200
                    ),
                ),
                (
                    "landing_page_name",
                    models.CharField(
                        help_text="Gophish landing page name.", max_length=200
                    ),
                ),
                ("landing_page_url", models.URLField()),
                ("times_used", models.PositiveIntegerField(default=0, editable=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SmartGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            (
                                "repeat_clickers",
                                "Repeat clickers (failed 2+ campaigns)",
                            ),
                            ("high_risk", "High current risk score"),
                            ("new_hires", "New hires (recently added)"),
                            ("all", "Everyone active"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_hire_days",
                    models.PositiveIntegerField(
                        default=30, help_text="For the new-hires rule."
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: restrict the rule to one department.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_groups",
                        to="employees.department",
                    ),
                ),
            ],
        ),
    ]
