# Generated by Django 5.2.17 on 2026-09-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_template_catalog_smart_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="target_smart_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dynamic audience, computed at launch. Overrides the target department when set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.smartgroup",
            ),
        ),
    ]
