# Generated by Django 5.2.17 on 2026-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_smart_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Also the template name in the phishing engine.', max_length=200, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('layout', models.CharField(choices=[('corporate', 'Corporate notice (header bar)'), ('alert', 'Urgent alert (red header bar)'), ('minimal', 'Plain internal memo')], default='corporate', max_length=20)),
                ('brand_name', models.CharField(blank=True, help_text='Shown in the header bar when there is no logo, e.g. IT Service Desk.', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text="Optional image URL the recipient's mail client can reach, e.g. a hosted logo.")),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Blank line = new paragraph. Start a line with "- " for a bullet. {{.FirstName}} is filled in per person.')),
                ('button_label', models.CharField(blank=True, help_text='The call to action. Leave blank for no button. Clicks are tracked automatically.', max_length=80)),
                ('footer_note', models.CharField(blank=True, help_text='Small print, e.g. Sent by People Team. Please do not reply.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
