# Generated by Django 5.2.17 on 2026-09-24 10:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_email_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Or an image URL the recipient's mail client can reach. An uploaded logo wins."),
        ),
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_name', models.CharField(max_length=64, unique=True)),
                ('original_name', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional banner image shown under the header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.emailimage'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.emailimage'),
        ),
        migrations.CreateModel(
            name='LandingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Also the landing-page name in the phishing engine.', max_length=200, unique=True)),
                ('layout', models.CharField(choices=[('signin', 'Sign-in card'), ('document', 'Document viewer'), ('verify', 'Account verification (split screen)')], default='signin', max_length=20)),
                ('brand_name', models.CharField(blank=True, help_text='Shown when there is no logo.', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='Or a logo image URL. An uploaded logo wins.')),
                ('accent_color', models.CharField(default='#0b5fff', help_text='Button and highlight colour, like #0b5fff.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a colour like #0b5fff.')])),
                ('heading', models.CharField(default='Sign in', max_length=200)),
                ('subtext', models.CharField(blank=True, max_length=300)),
                ('username_label', models.CharField(default='Work email', max_length=60)),
                ('ask_password', models.BooleanField(default=True, help_text='Show a password field. It is never captured or stored.')),
                ('button_label', models.CharField(default='Sign in', max_length=60)),
                ('footer_note', models.CharField(blank=True, max_length=300)),
                ('redirect_url', models.URLField(blank=True, help_text='Where to send people after they submit. Blank = the teachable-moment page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.emailimage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
