# Generated by Django 5.2.17 on 2026-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_images_and_landing_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='body_html',
            field=models.TextField(blank=True, help_text='The composed message (sanitised). Takes over from the older text fields.'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='layout',
            field=models.CharField(choices=[('minimal', 'Plain email (like Outlook)'), ('corporate', 'Branded notice (blue header bar)'), ('alert', 'Urgent alert (red header bar)')], default='minimal', max_length=20),
        ),
    ]
