# Generated by Django 5.2.17 on 2026-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_email_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='copy_to',
            field=models.TextField(blank=True, help_text='Extra addresses (not employees) that get their own copy of the email at launch, comma-separated.'),
        ),
    ]
