# Generated by Django 5.2.17 on 2026-09-24 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_copy_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='name',
            field=models.CharField(help_text='Also the template name in the phishing engine.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[^/\\\\]+$', "Names can't contain / or \\.")]),
        ),
        migrations.AlterField(
            model_name='landingdraft',
            name='name',
            field=models.CharField(help_text='Also the landing-page name in the phishing engine.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[^/\\\\]+$', "Names can't contain / or \\.")]),
        ),
    ]
