# Generated by Django 5.2.17 on 2026-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_name_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingdraft',
            name='custom_html',
            field=models.TextField(blank=True, help_text='For a cloned page: the sanitised page itself.'),
        ),
        migrations.AddField(
            model_name='landingdraft',
            name='source_url',
            field=models.URLField(blank=True, help_text='For a cloned page: the address it was copied from.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landingdraft',
            name='layout',
            field=models.CharField(choices=[('signin', 'Sign-in card'), ('document', 'Document viewer'), ('verify', 'Account verification (split screen)'), ('cloned', 'Cloned from a website')], default='signin', max_length=20),
        ),
    ]
