# Generated by Django 5.2.17 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'ordering': ['-occurred_at'], 'permissions': [('manage_user_access', 'Can manage staff accounts and roles')], 'verbose_name_plural': 'audit log entries'},
        ),
    ]
