# Generated by Django 5.1.4 on 2026-09-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_department_managers_alter_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='0 (lowest risk) to 100 (highest).', max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm_version', models.CharField(max_length=32)),
                ('contributing_metrics', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='employees.employee')),
            ],
            options={
                'ordering': ['-computed_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'computed_at'], name='risk_scorin_employe_27845e_idx')],
            },
        ),
    ]
