# Generated by Django 5.1.4 on 2026-09-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_delivered', 'Email Delivered'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('credential_attempt', 'Credential Attempt'), ('phishing_reported', 'Phishing Reported'), ('training_assigned', 'Training Assigned'), ('training_started', 'Training Started'), ('training_completed', 'Training Completed'), ('quiz_completed', 'Quiz Completed')], max_length=32)),
                ('source', models.CharField(choices=[('gophish', 'Gophish'), ('django', 'Django'), ('manual', 'Manual')], max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='campaigns.campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'occurred_at'], name='events_even_employe_bb437a_idx'), models.Index(fields=['campaign', 'event_type'], name='events_even_campaig_1b05f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_event_source_external_id')],
            },
        ),
    ]
