"""
Compliance evidence package: one ZIP an auditor can be handed for the
"security awareness training and phishing-resilience" control family. It is
commonly used as supporting evidence for ISO/IEC 27001:2022 Annex A 6.3
(information security awareness, education and training) and SOC 2 (CC1.4 /
CC2.2). Which controls it satisfies is the auditor's call, so the package says
what it contains and how it was produced, not that it "certifies" anything.

Integrity: manifest.json lists the SHA-256 of every file, SHA256SUMS.txt lets
anyone check with `sha256sum -c`, and the archive's own hash is stored on the
GeneratedReport row.
"""

import hashlib
import io
import json
import zipfile

from apps.core.models import AuditLogEntry
from apps.risk_scoring import analytics

from . import exports, pdf
from .data import ReportData

FIXED_TIMESTAMP = (2000, 1, 1, 0, 0, 0)  # entries carry no wall-clock time, so the bytes depend only on content


def _audit_log_csv(data: ReportData) -> tuple[bytes, int]:
    entries = AuditLogEntry.objects.filter(
        occurred_at__gte=data.period_start_dt, occurred_at__lte=data.as_of
    ).select_related("actor").order_by("occurred_at")
    rows = [
        {
            "occurred_at": entry.occurred_at.isoformat(),
            "actor": entry.actor.get_username() if entry.actor else "system",
            "action": entry.action,
            "target": entry.target_description,
        }
        for entry in entries
    ]
    columns = [("occurred_at", "Occurred at (UTC)"), ("actor", "Actor"), ("action", "Action"), ("target", "Target")]
    return exports.to_csv(columns, rows), len(rows)


def _methodology(data: ReportData) -> bytes:
    text = f"""# Methodology

Report period: {data.period_start} to {data.period_end}
Figures as of: {data.as_of.isoformat()}
Scope: {data.scope.label}
Risk-scoring algorithm: {data.algorithm_version}

## How risk scores are computed
- Source: the platform's append-only event log. Events are never edited or deleted, so any past
  date can be recomputed exactly; the figures in this package were recomputed as of the date above.
- Per campaign only the worst outcome counts: submitting data = 50 points, clicking the link = 25.
- Reporting the email earns a 15-point credit (per campaign).
- Each failed campaign after the first adds a 10-point repeat-failure penalty.
- Every contribution decays with a 180-day half-life. Scores are clamped to 0-100 (higher = riskier).
- Risk levels: medium from {analytics.MEDIUM_RISK_THRESHOLD}, high from {analytics.HIGH_RISK_THRESHOLD}.
- Email-open events are excluded (mail clients prefetch tracking pixels, so they do not reflect behaviour).
- Training and quiz completion are NOT part of the score; they are reported separately as compliance metrics.
- Passwords are never captured or stored by the platform.

## Files
See README.txt. Verify integrity with: sha256sum -c SHA256SUMS.txt
"""
    return text.encode("utf-8")


def _readme(data: ReportData, generated_by: str, generated_at: str, files: list[dict]) -> bytes:
    lines = [
        "SECURITY AWARENESS — COMPLIANCE EVIDENCE PACKAGE",
        "",
        f"Period:       {data.period_start} to {data.period_end}",
        f"As of:        {data.as_of.isoformat()}",
        f"Scope:        {data.scope.label}",
        f"Generated by: {generated_by}",
        f"Generated at: {generated_at}",
        f"Algorithm:    {data.algorithm_version}",
        "",
        "Contents",
        "--------",
    ]
    lines += [f"{f['name']:<28} {f['description']}" for f in files]
    lines += [
        "",
        "Notes",
        "-----",
        "- This package is supporting evidence for security awareness / phishing-resilience controls",
        "  (for example ISO/IEC 27001:2022 Annex A 6.3 and SOC 2 CC1.4/CC2.2). Mapping to a control is the auditor's decision.",
        "- Individual-level files contain personal data; handle under your data-protection policy.",
        "- Integrity: run `sha256sum -c SHA256SUMS.txt`. manifest.json lists the same hashes with row counts.",
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def build_evidence_package(data: ReportData, generated_by: str, generated_at: str) -> tuple[bytes, int]:
    risk_bytes, risk_rows = exports.risk_scores_csv(data)
    campaign_bytes, campaign_rows = exports.campaigns_csv(data)
    department_bytes, department_rows = exports.departments_csv(data)
    training_bytes, training_rows = exports.training_csv(data)
    audit_bytes, audit_rows = _audit_log_csv(data)

    files = [
        {"name": "executive_summary.pdf", "description": "Headline results, trend, campaigns, departments", "bytes": pdf.render_executive_summary(data), "rows": None},
        {"name": "campaigns.csv", "description": "Every simulation in the period and its results", "bytes": campaign_bytes, "rows": campaign_rows},
        {"name": "departments.csv", "description": "Risk and training completion by department", "bytes": department_bytes, "rows": department_rows},
        {"name": "employee_risk_scores.csv", "description": "Per-employee risk score at the report date", "bytes": risk_bytes, "rows": risk_rows},
        {"name": "training_assignments.csv", "description": "Every training assignment and its status", "bytes": training_bytes, "rows": training_rows},
        {"name": "audit_log.csv", "description": "Administrative actions in the period (launches, approvals, exports)", "bytes": audit_bytes, "rows": audit_rows},
        {"name": "methodology.md", "description": "How the figures were produced", "bytes": _methodology(data), "rows": None},
    ]
    for f in files:
        f["sha256"] = hashlib.sha256(f["bytes"]).hexdigest()

    manifest = {
        "package": "security-awareness-evidence",
        "period_start": str(data.period_start),
        "period_end": str(data.period_end),
        "as_of": data.as_of.isoformat(),
        "scope": data.scope.label,
        "algorithm_version": data.algorithm_version,
        "generated_by": generated_by,
        "generated_at": generated_at,
        "files": [{"name": f["name"], "sha256": f["sha256"], "bytes": len(f["bytes"]), "rows": f["rows"]} for f in files],
    }
    readme = _readme(data, generated_by, generated_at, files + [{"name": "manifest.json", "description": "File list with SHA-256 and row counts"}, {"name": "SHA256SUMS.txt", "description": "Checksums for sha256sum -c"}])
    manifest_bytes = json.dumps(manifest, indent=2).encode("utf-8")

    entries = {f["name"]: f["bytes"] for f in files}
    entries["README.txt"] = readme
    entries["manifest.json"] = manifest_bytes
    sums = "".join(f"{hashlib.sha256(content).hexdigest()}  {name}\n" for name, content in sorted(entries.items()))
    entries["SHA256SUMS.txt"] = sums.encode("utf-8")

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for name in sorted(entries):
            info = zipfile.ZipInfo(name, date_time=FIXED_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, entries[name])
    return buffer.getvalue(), risk_rows + training_rows + campaign_rows
