# Generated by Django 5.2.17 on 2026-09-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_is_active"),
        ("training", "0002_alter_quiz_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "repeat_every_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Re-enrol after this many days (365 = annual).",
                    ),
                ),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days each person has to complete it."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = everyone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_policies",
                        to="employees.department",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="training.trainingmodule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "training policies",
            },
        ),
    ]
