# Generated by Django 5.2.17 on 2026-09-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='content_url',
            field=models.URLField(blank=True, help_text='Optional. Only for training hosted elsewhere; leave blank when the module has slides.'),
        ),
        migrations.CreateModel(
            name='TrainingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Blank line = new paragraph. Start a line with "- " for a bullet.')),
                ('callout', models.CharField(blank=True, help_text='Optional highlighted takeaway.', max_length=300)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='training.trainingmodule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
