# Generated by Django 5.2.17 on 2026-09-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_slides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='waived_at',
            field=models.DateTimeField(blank=True, help_text='A documented exception: the assignment no longer counts as outstanding or overdue, and is never counted as completed.', null=True),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
