# Generated by Django 5.1.4 on 2026-09-22 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text="Django users in the Department Manager group whose admin access is scoped to this department. Distinct from `manager` above — that's an Employee (org-chart fact), this is a User (login/permission fact).", related_name='managed_departments_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The employee who manages this department (org-chart fact, not a login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
        ),
    ]
