# Generated by Django 5.2.17 on 2026-09-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_department_managers_alter_department_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "permissions": [
                    ("export_employee_data", "Can export employee data as CSV")
                ]
            },
        ),
    ]
