# Generated by Django 5.2.17 on 2026-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_export_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Offboarded employees are deactivated, never deleted — their event history is immutable.",
            ),
        ),
    ]
