# Generated by Django 5.2.17 on 2026-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When they were offboarded. Starts the privacy-retention clock; cleared if they are reactivated.', null=True),
        ),
    ]
