# Generated by Django 5.2.17 on 2026-09-24 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_deactivated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exempt_reason',
            field=models.CharField(blank=True, help_text='Why this person is excluded from simulations (legal hold, leave, accessibility...). Required when exempt.', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='exempt_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exempt_set_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='exempt_until',
            field=models.DateField(blank=True, help_text='The exemption lapses automatically after this date. Leave empty only for a documented open-ended reason.', null=True),
        ),
    ]
