# Generated by Django 5.2.17 on 2026-09-24 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_employee_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=300)),
                ("sender", models.CharField(blank=True, max_length=300)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="What the employee said about it."
                    ),
                ),
                (
                    "headers",
                    models.TextField(
                        blank=True,
                        help_text="Raw headers, if the integration supplied them.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "Employee portal"),
                            ("api", "API / mail integration"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("safe", "Safe"),
                            ("spam", "Spam"),
                            ("malicious", "Malicious"),
                            ("simulation", "Our simulation"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("triage_notes", models.TextField(blank=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_emails",
                        to="employees.employee",
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["verdict", "reported_at"],
                        name="intake_repo_verdict_e16d12_idx",
                    )
                ],
            },
        ),
    ]
