# Generated by Django 5.2.17 on 2026-09-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What this key is for, e.g. 'content-drafting bot'.",
                        max_length=120,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("hashed_key", models.CharField(editable=False, max_length=64)),
                (
                    "scopes",
                    models.JSONField(
                        default=list, help_text="Which operations this key may perform."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="After this the key stops working. Blank = no expiry.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set to disable the key immediately.",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The key acts as this user and can never exceed their permissions.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "ordering": ["-created_at"],
            },
        ),
    ]
